version: "0.2"
language: en
ignorePaths:
  - "**/node_modules/**"
  - package-lock.json
  - "**/.gitignore"
  - "**/.mega-linter.yml"
  - "**/.github/CODEOWNERS"
  - "**/.github/workflows/**"
  - "**/.git/**"
  - "**/vscode-extension/**"
  - .vscode
  - report
words:
  - beholdenkey
  - CODEOWNERS
